python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Gowal2021Improving_70_16_ddpm_100m_cifar10_Adam_ReduceLROnPlateau_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Wang2023Better_WRN-70-16_cifar10_Adam_ReduceLROnPlateau_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Gowal2021Improving_28_10_ddpm_100m_cifar10_Adam_ReduceLROnPlateau_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Wang2023Better_WRN-28-10_cifar10_SGD_CosineAnnealingLR_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Pang2022Robustness_WRN28_10_cifar10_Adam_ReduceLROnPlateau_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Pang2022Robustness_WRN70_16_cifar10_SGD_CosineAnnealingLR_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Pang2022Robustness_WRN28_10_cifar10_SGD_CosineAnnealingLR_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Gowal2021Improving_70_16_ddpm_100m_cifar10_SGD_CosineAnnealingLR_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Wang2023Better_WRN-28-10_cifar10_Adam_ReduceLROnPlateau_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Gowal2021Improving_R18_ddpm_100m_cifar10_SGD_CosineAnnealingLR_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Rebuffi2021Fixing_106_16_cutmix_ddpm_cifar10_Adam_ReduceLROnPlateau_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Gowal2021Improving_R18_ddpm_100m_cifar10_Adam_ReduceLROnPlateau_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Gowal2021Improving_28_10_ddpm_100m_cifar10_SGD_CosineAnnealingLR_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Sehwag2021Proxy_ResNest152_cifar10_SGD_CosineAnnealingLR_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Wang2023Better_WRN-70-16_cifar10_SGD_CosineAnnealingLR_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Pang2022Robustness_WRN70_16_cifar10_Adam_ReduceLROnPlateau_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Rebuffi2021Fixing_106_16_cutmix_ddpm_cifar10_SGD_CosineAnnealingLR_LL.pkl
python run_attack.py --batch 500 --steps 100 --dataset_percent 1 --fmn_config ./Configs/ModelsBestConfigs/final_configs/Sehwag2021Proxy_ResNest152_cifar10_Adam_ReduceLROnPlateau_LL.pkl
